In [ ]:
import pandas as pd
import json

from scipy.stats import anova

In [16]:
with open(f"../responses/result_eval.json", 'r') as result_file:

    results = json.load(result_file)
results_df = pd.DataFrame(results)
multi_index_results_df = results_df.set_index(['embedder', 'generator', 'distance_metric']).sort_index()
multi_index_results_df

                                                                                context_utilization  \
embedder                       generator                     distance_metric
Qwen3-Embedding-8B             Ministral-3-14B-Instruct-2512 cosine_similarity                  0.0
                                                             cosine_similarity                  0.0
                                                             cosine_similarity                  0.0
                                                             cosine_similarity                  0.0
                                                             cosine_similarity                  0.0
...                                                                                             ...
multilingual-e5-large-instruct Qwen3-30B-A3B-Instruct-2507   manhattan                          0.0
                                                             manhattan                          0.0
                                                             manhattan                          0.0
                                                             manhattan                          0.0
                                                             manhattan                          0.0

                                                                                answer_relevancy  \
embedder                       generator                     distance_metric
Qwen3-Embedding-8B             Ministral-3-14B-Instruct-2512 cosine_similarity          0.000000
                                                             cosine_similarity          0.000000
                                                             cosine_similarity          0.308273
                                                             cosine_similarity          0.233082
                                                             cosine_similarity          0.453505
...                                                                                          ...
multilingual-e5-large-instruct Qwen3-30B-A3B-Instruct-2507   manhattan                       NaN
                                                             manhattan                       NaN
                                                             manhattan                       NaN
                                                             manhattan                       NaN
                                                             manhattan                       NaN

                                                                                faithfullness  \
embedder                       generator                     distance_metric
Qwen3-Embedding-8B             Ministral-3-14B-Instruct-2512 cosine_similarity            NaN
                                                             cosine_similarity            NaN
                                                             cosine_similarity            NaN
                                                             cosine_similarity            NaN
                                                             cosine_similarity            NaN
...                                                                                       ...
multilingual-e5-large-instruct Qwen3-30B-A3B-Instruct-2507   manhattan                    NaN
                                                             manhattan                    NaN
                                                             manhattan                    NaN
                                                             manhattan                    NaN
                                                             manhattan                    NaN

                                                                                                user_prompt  \
embedder                       generator                     distance_metric
Qwen3-Embedding-8B             Ministral-3-14B-Instruct-2512 cosine_similarity                      Crailoo
                                                             cosine_similarity                     Schiphol
                                                             cosine_similarity    Zandspektakel Julianadorp
                                                             cosine_similarity  De blaffende vis Koningsdag
                                                             cosine_similarity                 Fotofestival
...                                                                                                     ...
multilingual-e5-large-instruct Qwen3-30B-A3B-Instruct-2507   manhattan             Vertel me over Amsterdam
                                                             manhattan             Warmte-koudeopslag (WKO)
                                                             manhattan                 De Heg marineterrein
                                                             manhattan                          Trekkertrek
                                                             manhattan                                Texel

                                                                               prompt_type  \
embedder                       generator                     distance_metric
Qwen3-Embedding-8B             Ministral-3-14B-Instruct-2512 cosine_similarity    question
                                                             cosine_similarity    question
                                                             cosine_similarity    question
                                                             cosine_similarity    question
                                                             cosine_similarity    question
...                                                                                    ...
multilingual-e5-large-instruct Qwen3-30B-A3B-Instruct-2507   manhattan            question
                                                             manhattan            question
                                                             manhattan            question
                                                             manhattan            question
                                                             manhattan            question

                                                                                faithfulness
embedder                       generator                     distance_metric
Qwen3-Embedding-8B             Ministral-3-14B-Instruct-2512 cosine_similarity           NaN
                                                             cosine_similarity           NaN
                                                             cosine_similarity           NaN
                                                             cosine_similarity           NaN
                                                             cosine_similarity           NaN
...                                                                                      ...
multilingual-e5-large-instruct Qwen3-30B-A3B-Instruct-2507   manhattan                   NaN
                                                             manhattan                   NaN
                                                             manhattan                   NaN
                                                             manhattan                   NaN
                                                             manhattan                   NaN

[450 rows x 6 columns]

In [17]:
metrics = ['mean', 'std']

grouped = results_df.groupby(['embedder', 'generator', 'distance_metric'], dropna=False).agg({'context_utilization' : metrics,
                                                                                              'answer_relevancy' : metrics,
                                                                                              'faithfullness' : metrics})
grouped

                                                                                        context_utilization  \
                                                                                                       mean
embedder                       generator                              distance_metric
Qwen3-Embedding-8B             Ministral-3-14B-Instruct-2512          cosine_similarity            0.040000
                                                                      manhattan                    0.100000
                               NVIDIA-Nemotron-3-Super-120B-A12B-BF16 cosine_similarity            0.068182
                                                                      manhattan                    0.142857
                               Qwen3-30B-A3B-Instruct-2507            cosine_similarity            0.000000
                                                                      manhattan                    0.000000
bge-m3                         Ministral-3-14B-Instruct-2512          cosine_similarity            0.000000
                                                                      manhattan                    0.203333
                               NVIDIA-Nemotron-3-Super-120B-A12B-BF16 cosine_similarity            0.087963
                                                                      manhattan                    0.436508
                               Qwen3-30B-A3B-Instruct-2507            cosine_similarity            0.000000
                                                                      manhattan                    0.000000
multilingual-e5-large-instruct Ministral-3-14B-Instruct-2512          cosine_similarity            0.000000
                                                                      manhattan                    0.196667
                               NVIDIA-Nemotron-3-Super-120B-A12B-BF16 cosine_similarity            0.057018
                                                                      manhattan                    0.228261
                               Qwen3-30B-A3B-Instruct-2507            cosine_similarity            0.000000
                                                                      manhattan                    0.000000

                                                                                                   \
                                                                                              std
embedder                       generator                              distance_metric
Qwen3-Embedding-8B             Ministral-3-14B-Instruct-2512          cosine_similarity  0.200000
                                                                      manhattan          0.235702
                               NVIDIA-Nemotron-3-Super-120B-A12B-BF16 cosine_similarity  0.233781
                                                                      manhattan          0.358569
                               Qwen3-30B-A3B-Instruct-2507            cosine_similarity  0.000000
                                                                      manhattan          0.000000
bge-m3                         Ministral-3-14B-Instruct-2512          cosine_similarity  0.000000
                                                                      manhattan          0.315568
                               NVIDIA-Nemotron-3-Super-120B-A12B-BF16 cosine_similarity  0.265795
                                                                      manhattan          0.357368
                               Qwen3-30B-A3B-Instruct-2507            cosine_similarity  0.000000
                                                                      manhattan          0.000000
multilingual-e5-large-instruct Ministral-3-14B-Instruct-2512          cosine_similarity  0.000000
                                                                      manhattan          0.299382
                               NVIDIA-Nemotron-3-Super-120B-A12B-BF16 cosine_similarity  0.171352
                                                                      manhattan          0.381234
                               Qwen3-30B-A3B-Instruct-2507            cosine_similarity  0.000000
                                                                      manhattan          0.000000

                                                                                        answer_relevancy  \
                                                                                                    mean
embedder                       generator                              distance_metric
Qwen3-Embedding-8B             Ministral-3-14B-Instruct-2512          cosine_similarity         0.102754
                                                                      manhattan                 0.235026
                               NVIDIA-Nemotron-3-Super-120B-A12B-BF16 cosine_similarity         0.423791
                                                                      manhattan                 0.339159
                               Qwen3-30B-A3B-Instruct-2507            cosine_similarity              NaN
                                                                      manhattan                      NaN
bge-m3                         Ministral-3-14B-Instruct-2512          cosine_similarity         0.278981
                                                                      manhattan                 0.334962
                               NVIDIA-Nemotron-3-Super-120B-A12B-BF16 cosine_similarity         0.280540
                                                                      manhattan                 0.295491
                               Qwen3-30B-A3B-Instruct-2507            cosine_similarity              NaN
                                                                      manhattan                      NaN
multilingual-e5-large-instruct Ministral-3-14B-Instruct-2512          cosine_similarity         0.171200
                                                                      manhattan                 0.235742
                               NVIDIA-Nemotron-3-Super-120B-A12B-BF16 cosine_similarity         0.370056
                                                                      manhattan                 0.297480
                               Qwen3-30B-A3B-Instruct-2507            cosine_similarity              NaN
                                                                      manhattan                      NaN

                                                                                                   \
                                                                                              std
embedder                       generator                              distance_metric
Qwen3-Embedding-8B             Ministral-3-14B-Instruct-2512          cosine_similarity  0.170653
                                                                      manhattan          0.255265
                               NVIDIA-Nemotron-3-Super-120B-A12B-BF16 cosine_similarity  0.266731
                                                                      manhattan          0.160550
                               Qwen3-30B-A3B-Instruct-2507            cosine_similarity       NaN
                                                                      manhattan               NaN
bge-m3                         Ministral-3-14B-Instruct-2512          cosine_similarity  0.237353
                                                                      manhattan          0.295134
                               NVIDIA-Nemotron-3-Super-120B-A12B-BF16 cosine_similarity  0.225706
                                                                      manhattan          0.163561
                               Qwen3-30B-A3B-Instruct-2507            cosine_similarity       NaN
                                                                      manhattan               NaN
multilingual-e5-large-instruct Ministral-3-14B-Instruct-2512          cosine_similarity  0.246395
                                                                      manhattan          0.262751
                               NVIDIA-Nemotron-3-Super-120B-A12B-BF16 cosine_similarity  0.239374
                                                                      manhattan          0.131640
                               Qwen3-30B-A3B-Instruct-2507            cosine_similarity       NaN
                                                                      manhattan               NaN

                                                                                        faithfullness  \
                                                                                                 mean
embedder                       generator                              distance_metric
Qwen3-Embedding-8B             Ministral-3-14B-Instruct-2512          cosine_similarity           NaN
                                                                      manhattan                   NaN
                               NVIDIA-Nemotron-3-Super-120B-A12B-BF16 cosine_similarity           NaN
                                                                      manhattan                   NaN
                               Qwen3-30B-A3B-Instruct-2507            cosine_similarity           NaN
                                                                      manhattan                   NaN
bge-m3                         Ministral-3-14B-Instruct-2512          cosine_similarity           NaN
                                                                      manhattan                   NaN
                               NVIDIA-Nemotron-3-Super-120B-A12B-BF16 cosine_similarity           NaN
                                                                      manhattan                   NaN
                               Qwen3-30B-A3B-Instruct-2507            cosine_similarity           NaN
                                                                      manhattan                   NaN
multilingual-e5-large-instruct Ministral-3-14B-Instruct-2512          cosine_similarity           NaN
                                                                      manhattan                   NaN
                               NVIDIA-Nemotron-3-Super-120B-A12B-BF16 cosine_similarity           NaN
                                                                      manhattan                   NaN
                               Qwen3-30B-A3B-Instruct-2507            cosine_similarity           NaN
                                                                      manhattan                   NaN


                                                                                        std
embedder                       generator                              distance_metric
Qwen3-Embedding-8B             Ministral-3-14B-Instruct-2512          cosine_similarity NaN
                                                                      manhattan         NaN
                               NVIDIA-Nemotron-3-Super-120B-A12B-BF16 cosine_similarity NaN
                                                                      manhattan         NaN
                               Qwen3-30B-A3B-Instruct-2507            cosine_similarity NaN
                                                                      manhattan         NaN
bge-m3                         Ministral-3-14B-Instruct-2512          cosine_similarity NaN
                                                                      manhattan         NaN
                               NVIDIA-Nemotron-3-Super-120B-A12B-BF16 cosine_similarity NaN
                                                                      manhattan         NaN
                               Qwen3-30B-A3B-Instruct-2507            cosine_similarity NaN
                                                                      manhattan         NaN
multilingual-e5-large-instruct Ministral-3-14B-Instruct-2512          cosine_similarity NaN
                                                                      manhattan         NaN
                               NVIDIA-Nemotron-3-Super-120B-A12B-BF16 cosine_similarity NaN
                                                                      manhattan         NaN
                               Qwen3-30B-A3B-Instruct-2507            cosine_similarity NaN
                                                                      manhattan         NaN